[tool.poetry]

name = "template-python"
version = "2.0.2"
description = "A template for Python libraries."
authors = ["Jerome Guibert <jguibert@gmail.com>"]


[tool.poetry.dependencies]
python= "^3"
cookiecutter = "*"
