
docs_dir: docs
# in order to expose with github page project
site_dir: site

# Project information
site_name: {{cookiecutter.project_name}}
site_url: https://{{cookiecutter.github_username}}.github.io/{{cookiecutter.github_repo}}/
site_description: {{cookiecutter.project_short_description}}
site_author: {{cookiecutter.full_name}}

# Repository
repo_name: "{{cookiecutter.github_username}}/{{cookiecutter.github_repo}}"
repo_url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.github_repo}}
# Copyright
copyright: "Copyright © {% now 'utc', '%Y' %} <a href=\"https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.github_repo}}\">{{cookiecutter.full_name}}</a>"

# Configuration
theme:
  name: "material"
  language: "en"
  palette:
    primary: "deep purple"
    accent: "light-blue"
  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"
  feature:
    tabs: false

nav:
  - Home: index.md
  - API:
      - overview: api-overview.md
      - main: api/index.md
  - About:
      - Contributing: contributing.md
      - Documentation: documentation.md
      - Release Notes: changelog.md
      - License: license.md
      - Code of Conduct: code_of_conduct.md

# Customization
extra:
  social:
    - type: "github"
      link: "https://github.com/{{cookiecutter.github_username}}"


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown
